# 파이썬 기초

### 변수
* 연산중 필요한 데이터를 컴퓨터 메모리에 저장하는 공간
* 변수는 데이터가 저장되는 메모리의 위치(주소)를 기억
* 변수에 데이터를 저장하기 위해서 대입연산자(=)를 사용

```
변수명 = 변수에 저장할 값
```

In [1]:
#변수 활용 예제
val = 5
val 

5

In [2]:
#변수 메모리 주소 확인
id(val)

140727499846568

In [3]:
#연산 결과 저장
val = 5 + 7
val

12

In [4]:
#변수를 이용한 연산
val1 = 10
val2 = 20
val3 = val1 + val2
val3

30

### 자료형(Data Type)

#### 숫자형
* 정수형(int) : 소수점이 없는 숫자. 1, -23, 0 등
* 실수형(float) : 소수점이 있는 숫자. 3.14, -0.5, 12e11, 13E-4
* 8진수 : 0o123, 0O45 등
* 16진수 : 0x34, 0X1AB, 0x23cd 등

In [11]:
# 숫자형 자료형 예제
val1 = 1
val2 = -23
val3 = 3.14
val4 = -0.5
val5 = 12e5
val6 = 13e-3
val7 = 0o123
val8 = 0x9abcdef

print(val1, type(val1))
print(val2, type(val2))
print(val3, type(val3))
print(val4, type(val4))
print(val5, type(val5))
print(val6, type(val6))
print(val7, type(val7))
print(val8, type(val8))

1 <class 'int'>
-23 <class 'int'>
3.14 <class 'float'>
-0.5 <class 'float'>
1200000.0 <class 'float'>
0.013 <class 'float'>
83 <class 'int'>
162254319 <class 'int'>


In [12]:
이름 = '유병윤'
나이 = 27

print(이름)
print(나이)

유병윤
27


#### 논리형
* 비교연산이나 논리연산의 결과를 표현하는 자료형
* 조건을 만족하면 참(True), 만족하지 않으면 거짓(False)으로 표현
* 첫글자는 대문자

In [13]:
a = True
b = False

print(a, type(a))
print(b, type(b))

True <class 'bool'>
False <class 'bool'>


#### 산술연산자
* 숫자를 연산하는데 사용하는 연산 기호
* 더하기(+), 빼기(-), 곱하기(*), 나누기(/)를 연산하는 사칙연산
* 나눗셈의 몫(//)을 구하는 연산자, 나머지(%)를 구하는 연산자, 승수(거듭제곱)(**)를 구하는 연산자가 있음.

In [14]:
#산술연산자 실습
a = 7
b = 3
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a // b)
print(a % b)
print(a ** b)

10
4
21
2.3333333333333335
2
1
343


#### 비교연산자
* 두 수의 크기를 비교하는 연산자
* 크다(>), 크거나 같다(>=), 작다(<), 작거나 같다(=<), 같다(==), 같지않다(!=)가 있음.

In [15]:
#비교연산자 예제
a = 3
b = 4

print(a > b)
print(a >= b)
print(a < b)
print(a <= b)
print(a == b)
print(a != b)


False
False
True
True
False
True


#### 논리연산자
* 서로 다른 조건의 논리적 연산에 사용되는 연산자
* 연산자에는  and, or, not이 있음

In [16]:
# and 연산자
print(False and False)
print(False and True)
print(True and False)
print(True and True)

False
False
False
True


In [17]:
# or 연산자
print(False or False)
print(False or True)
print(True or False)
print(True or True)

False
True
True
True


In [18]:
# not 연산자
print(not False)
print(not True)


True
False


#### 문자열(String)
* 문자, 단어 , 숫자 등으로 구성된 문자들의 집합
* 큰따옴표(""), 작은따옴표('') 묶어서 사용

In [3]:
str1 = "Hello World"
str2 = 'Python is fun'
str3 = """안녕하세요.
파이썬입니다.
"""
str4 = '''반갑습니다.
잘부탁드립니다
ㅎㅎㅎ
'''

print(str1, type(str1))
print(str2, type(str2))
print(str3, type(str3))
print(str4, type(str4))

Hello World <class 'str'>
Python is fun <class 'str'>
안녕하세요.
파이썬입니다.
 <class 'str'>
반갑습니다.
잘부탁드립니다
ㅎㅎㅎ
 <class 'str'>


In [7]:
#이스케이프 코드
str1 = 'I\'m a boy'
str2 = 'hello python.\nthank you'

print(str1)
print(str2)

I'm a boy
hello python.
thank you


#### 문자열 연산자
* (+)연산자 :  문자열 연결

In [9]:
head = "Python"
tail = " is fun!"

print(head + tail)

Python is fun!


* (*) 연산자: 뒤에 곱해진 수만큼 문자열 반복

In [10]:
print(head * 2)

PythonPython


In [11]:
print("=" * 50)
print("My program")
print("=" * 50)

My program


* 문자열의 길이 구하기 : len() 함수

In [13]:
a = "Life is too short."
print(len(a))

18


In [15]:
print(a[2])

f


In [17]:
print(a[-6])

s


* 문자열 슬라이싱: 인덱스 범위를 지정하여 여러 문자를 추출하는 방법

[시작 인덱스번호 : 끝 인덱스번호 -1]

In [21]:
a[8:11]

'too'

In [27]:
a[-6:]

'short.'

In [28]:
a[:5]

'Life '

* 문자열 포맷팅

%s : 문자열  
%c : 1문자  
%d : 10진수 정수  
%f : 실수  
%o : 8진수  
%x : 16진수  
%% : % 문자  

In [29]:
#문자열 포맷팅 예제
"현재 온도는 %d도 입니다." % 34

'현재 온도는 34도 입니다.'

In [30]:
val1 = 35
"10진수 %d는 16진수 %x 입니다." %(val1, val1)

'10진수 35는 16진수 23 입니다.'

In [31]:
"%10s" % "python"

'    python'

In [32]:
"%-10s" % "python"

'python    '

In [44]:
"%0.2f" % 1.23656789

'1.24'

* format() 함수

In [45]:
"I eat {0} apples".format(3)

'I eat 3 apples'

In [49]:
"I eat {0} apples. so I was sick for {1} days.".format("five",3)

'I eat five apples. so I was sick for 3 days.'

In [54]:
"{0:>10}".format("hi")

'hi        '

In [55]:
"{0:<10}".format("hi")

'hi        '

In [56]:
"{0:^10}".format("hi")

'    hi    '

In [57]:
"{0:,}".format(123456789)

'123,456,789'

In [59]:
"{0:0.2f}".format(1.23656789)

'1.24'

In [60]:
"{0:=^10}".format("hi")

'====hi===='

* f문자열 포맷팅

In [64]:
name = '홍길동'
age = 25

f"나의 이름은 {name}입니다. 나이는 {age + 1}입니다."


'나의 이름은 홍길동입니다. 나이는 26입니다.'

* 문자열 관련 함수

In [68]:
#count()함수

a.count('i')

2

In [73]:
# find() 함수
a.find('i')

1

In [74]:
#index() 함수
a.index('s')

6

In [75]:
a.index('x')

ValueError: substring not found

In [78]:
#join() 함수

",".join("abcd")

'a,b,c,d'

In [79]:
#upper(), lower()함수
a = 'hi'
b = 'HI'
print(a.upper())
print(b.lower())

HI
hi


In [80]:
#왼쪽 공백 지우기 lstrip(), 오른쪽 공백 지우기 rstrip(), 양쪽 공백 지우기 strip()
a = " hi "
print(a.lstrip())
print(a.rstrip())
print(a.strip())

hi 
 hi
hi


In [81]:
#문자열 치환 replace()
a = "Life is too short"
a.replace("Life", "Your leg")

'Your leg is too short'

In [82]:
#문자열 나누기 split()
a.split()

['Life', 'is', 'too', 'short']

In [83]:
b = "a,b,c,d,e"
b.split(',')

['a', 'b', 'c', 'd', 'e']

#### 리스트(list)
* 여러개의 데이터를 하나의 집합으로 다루는 자료형
* []를 사용하여 원소를 정의하고 원소의 구분은 ,를 사용
* 여러가지 자료형을 섞어서 사용 가능

In [84]:
#list 기본 사용법
li = [1,2,3,4,5]
li

[1, 2, 3, 4, 5]

In [87]:
a = 10
b = 'python'
c = True
d = [6,7,8]
e = 2.15
list1 = [a,b,c,d,li,e]
list1

[10, 'python', True, [6, 7, 8], [1, 2, 3, 4, 5], 2.15]

In [88]:
#리스트 인덱싱
list1[0]

10

In [90]:
list1[3][1]

7

In [91]:
#리스트 슬라이싱
list1[1:4]

['python', True, [6, 7, 8]]

In [92]:
list1[-3:-1]

[[6, 7, 8], [1, 2, 3, 4, 5]]

In [93]:
#리스트 연산자(+,*)
list1 = [1,2,3]
list2 = [4,5,6]
list1 + list2

[1, 2, 3, 4, 5, 6]

In [94]:
list1 * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [96]:
#리스트 크기 구하기
len(list1)

3

In [100]:
#리스트 수정
list1[1] = 4
list1

[1, 4, 3]

In [103]:
#리스트 삭제
list1 = [1,2,3]
del list1[1]
list1

[1, 3]

In [104]:
#리스트 추가
list1.append(4)
list1

[1, 3, 4]

In [111]:
#리스트 삽입
list1.insert(1, 4)
list1

[1, 4, 3, 4]

In [112]:
#리스트 remove()
list1.remove(4)
list1

[1, 3, 4]

In [113]:
#리스트를 이용한 스택 구현
list2.append(1)
list2

[4, 5, 6, 1]

In [114]:
list2.pop()

1

In [115]:
list2

[4, 5, 6]

In [116]:
list1 = list1 + list2
list1

[1, 3, 4, 4, 5, 6]

In [117]:
#리스트 확장 extend()
list1.extend([7,8,9])
list1

[1, 3, 4, 4, 5, 6, 7, 8, 9]

In [118]:
list1.append([1,2,3])
list1

[1, 3, 4, 4, 5, 6, 7, 8, 9, [1, 2, 3]]

In [119]:
list1.count(4)


2

In [120]:
list1.index(8)

7

#### 튜플(tuple)
* 기본 구조는 리스트와 동일
* 한번 정의되면 수정, 추가 , 삭제 불가
* ()를 사용하여 원소를 정의하고 원소의 구분은 ,를 사용

In [121]:
#tuple 기본 사용
tp1 = (1, 2.3, 'abc', False,[4,5,6], (7,8))
tp1

(1, 2.3, 'abc', False, [4, 5, 6], (7, 8))

#### 딕셔너리(dictionary)
* 키(key): 값(value)이 쌍으로 구성
* {}를 사용하여 원소를 정의하고 원소 구분은 ,를 사용
* 인덱싱은 키를 사용하여 값에 접근

In [123]:
#딕셔너리 기본 사용
dic1 = {"name":"Kim","age":23}
dic1

{'name': 'Kim', 'age': 23}

In [124]:
dic1["name"]


'Kim'

In [125]:
#딕셔너리에 원소 추가
dic1['grade'] = [3.0,3.5,4.0]
dic1

{'name': 'Kim', 'age': 23, 'grade': [3.0, 3.5, 4.0]}

In [126]:
#딕셔너리 원소의 값 수정
dic1['grade'] = {'국어':3.0,'영어':3.5,'수학':4.0}
dic1

{'name': 'Kim', 'age': 23, 'grade': {'국어': 3.0, '영어': 3.5, '수학': 4.0}}

In [127]:
dic1['grade']['국어']

3.0

In [128]:
dic1.keys()

dict_keys(['name', 'age', 'grade'])

In [130]:
dic1.values()

dict_values(['Kim', 23, {'국어': 3.0, '영어': 3.5, '수학': 4.0}])

In [131]:
del dic1['grade']
dic1

{'name': 'Kim', 'age': 23}

### 제어문
* 프로그램의 일부가 어떤 조건을 만족하는 경우 실행되거나, 특정 처리를 반복할 때 사용
* 제어문에는 조건문(if)과 반복문(for,while)이 있음

#### 조건문 if
* 어떤 조건에 따라 처리를 분기 시킬 때 사용

```
#if문 구조

if 조건식 :
    처리1
elif 조건식 :
    처리2
else :
    처리 3  
```      

In [ ]:
#if문 구조
if 조건식 :
    처리1
    처리2
elif 조건식 :
    처리3
    처리4
else :
    처리5        

In [1]:
#조건 분기가 하나일 경우
a = int(input())
if a % 2 == 0 :
    print("짝수")

짝수


In [3]:
#조건 분기가 두개일경우
a = int(input())
if a % 2 == 0 :
    print("짝수")
else :
    print("홀수")    

짝수


In [6]:
#조건 분기가 여러개인 경우
a = int(input())
if a > 90 :
    print('A')
elif a > 80 :
    print('B')
elif a > 70 :
    print('C')
elif a > 60 :
    print('D')
else :
    print('F')      
print("프로그램 종료")             

F
프로그램 종료


#### 반복문 for
* 리스트의 개수 만큼 반복 처리

In [ ]:
#for문 구조
for 반복변수 in 리스트 :
    반복처리

In [7]:
list = [1,2,3]

for i in list :
    print(i)

1
2
3


In [8]:
for i in range(10) :
    print(i)

0
1
2
3
4
5
6
7
8
9


In [10]:
sum = 0
for i in range(1,11) :
    sum = sum + i
print(f"1~10 합 = {sum}")    

1~10 합 = 55


In [11]:
for i in range(1,11,2) :
    print(i)

1
3
5
7
9


[연습문제] 구구단 출력하는 코드 작성

In [20]:
for i in range (2,10) :
    print(f"{i:=^10}")
    for j in range (1, 10):
        print(f"{i} X {j} = {i * j}")
    print()    

====2=====
2 X 1 = 2
2 X 2 = 4
2 X 3 = 6
2 X 4 = 8
2 X 5 = 10
2 X 6 = 12
2 X 7 = 14
2 X 8 = 16
2 X 9 = 18

====3=====
3 X 1 = 3
3 X 2 = 6
3 X 3 = 9
3 X 4 = 12
3 X 5 = 15
3 X 6 = 18
3 X 7 = 21
3 X 8 = 24
3 X 9 = 27

====4=====
4 X 1 = 4
4 X 2 = 8
4 X 3 = 12
4 X 4 = 16
4 X 5 = 20
4 X 6 = 24
4 X 7 = 28
4 X 8 = 32
4 X 9 = 36

====5=====
5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45

====6=====
6 X 1 = 6
6 X 2 = 12
6 X 3 = 18
6 X 4 = 24
6 X 5 = 30
6 X 6 = 36
6 X 7 = 42
6 X 8 = 48
6 X 9 = 54

====7=====
7 X 1 = 7
7 X 2 = 14
7 X 3 = 21
7 X 4 = 28
7 X 5 = 35
7 X 6 = 42
7 X 7 = 49
7 X 8 = 56
7 X 9 = 63

====8=====
8 X 1 = 8
8 X 2 = 16
8 X 3 = 24
8 X 4 = 32
8 X 5 = 40
8 X 6 = 48
8 X 7 = 56
8 X 8 = 64
8 X 9 = 72

====9=====
9 X 1 = 9
9 X 2 = 18
9 X 3 = 27
9 X 4 = 36
9 X 5 = 45
9 X 6 = 54
9 X 7 = 63
9 X 8 = 72
9 X 9 = 81



#### 반복문 while
* 조건이 만족하는 동안 반복
* 조건에 따라 무한 반복할 가능성이 있으므로 반드시 탈출조건을 만들어야 함

In [ ]:
#while문 구조

while 조건식 :
    반복처리

In [21]:
n = 0
sum = 0
while n < 10 :
    n = n + 1
    sum = sum + n
    
print(sum)    

55


In [22]:
#반복문 탈출 방법
n = 0
while True :
    n = n + 1
    if n == 10 :
        break
print(n)    

10


In [24]:
# 반복 도중 건너뛰기(skip)
n = 0
while n < 10 :
    n = n + 1
    if n % 2 == 0 :
        continue
    print(n)

1
3
5
7
9


### 함수
* 특정 기능을 모듈화하여 필요시 호출하여 사용
* 사용자 정의 함수: 사용자(프로그래머)가 기능을 정의하여 사용하는것
* 내장 함수: 사용자가 자주 사용하는 기능을 파이썬에서 기본 제공하는 함수
* 람다 함수: 간단한 처리를 인라인(한줄)으로 정의할 때 사용. 복잡한 처리는 불가능

#### 사용자 정의 함수
* 사용자가 직접 정의하여 호출하는 함수

In [ ]:
# 사용자 정의 함수 구조
def 함수명 (매개변수1, 매개변수2, ...) :
    처리구문1
    처리구문2
    ...
    return 출력값

In [1]:
# 함수 정의 연습
def add(a, b) :
    return a + b

In [2]:
add(3,4)

7

In [3]:
#매개변수가 없는 함수
def say() :
    return 'hi'
say()

'hi'

In [4]:
#리턴값이 없는 함수
def add(a, b) :
    print("%d, %d의 합은 %d 입니다. " % (a,b,a+b))
add(7,8)

7, 8의 합은 15 입니다. 


In [12]:
#로컬변수(지역변수)와 글로벌변수(전역변수)
a = 1

def vartest(a) :
    a = a + 1

vartest(a)
print(a)
    

1


In [14]:
#글로벌(전역) 변수 선언 방법
a = 1

def vartest() :
    global a
    a = a + 1
vartest()
print(a)    

2


In [15]:
# 매개변수를 지정하여 호출
def sub(a, b) :
    return a - b
sub(5, 7)

-2

In [16]:
# 매개변수에 디폴트 값 설정
def cal(n1, n2, op='+') :
    if op == '+' :
        return n1 + n2
    if op == '-' :
        return n1 - n2
    if op == '*' :
        return n1 * n2
    if op == '/' :
        return n1 / n2
cal(3, 4, '*')

12

In [17]:
cal(4,5)

9

In [19]:
# 매개변수를 arguments로 정의하는 방법
def sum(*args) :
    result = 0
    for i in args :
        result = result + i
    return result    

sum(1,2,3,4,5)

15

In [20]:
print("a","b","c","d","e")

a b c d e


In [21]:
#리턴값이 여러개인 경우
def add_and_mul(a,b) :
    return a+b, a*b
add_result, mul_result = add_and_mul(3,4)

print(add_result,mul_result)

7 12


In [22]:
result = add_and_mul(5,6)
result

(11, 30)

#### 람다(lambda)함수
* 한 줄로 간결하게 함수를 정의
* 간단한 처리밖에 정의할 수 없음

In [ ]:
# lambda 함수 정의 방법
함수명 = lambda 매개변수1, 매개변수2, ... : 매개변수를 이용한 표현식


In [23]:
#lambda 함수 예제
add = lambda a, b : a + b

add(6,7)

13

In [25]:
div_mod = lambda a,b : (a//b, a%b)

div_mod(11,3)

(3, 2)

In [27]:
def even_mk() :
    even_list = []
    for i in range(1,11) :
        if i % 2 == 0 :
            even_list.append(i)
    return even_list   

even_mk()         

[2, 4, 6, 8, 10]

In [28]:
even_ld = lambda a, b : [i for i in range(a,b+1) if i % 2 == 0]

even_ld(1,10)

[2, 4, 6, 8, 10]

#### 파이썬 내장 함수
* 파이썬에서 기본 제공되는 함수들

In [ ]:
# sum()함수 : 리스트의 합계를 구하는 함수
li = [1,2,3,4,5,6,7,8,9]
sum(li)

In [39]:
#min(), max() 함수
print(min(li), max(li))

1 9


In [41]:
#int()함수
str2int = int("12345") #문자열을 정수로
float2int = int(3.94) # 실수를 정수로

print(str2int, float2int)

12345 3


In [43]:
int('1011',2)

11

In [44]:
int('167',8)

119

In [46]:
int('a1b3',16)

41395

In [42]:
#Str() 함수
str(3.14)

'3.14'

In [47]:
str(1234)

'1234'

In [50]:
#round()함수
print(round(3.14), round(6.547821, 2))

3 6.55


In [51]:
#input()함수 : 키보드로부터 데이터를 입력받는 함수
#입력받은 값은 모두 문자열로 취금
num = input()
print(num, type(num))

123 <class 'str'>


In [52]:
num = input("1~10 사이의 숫자를 입력해 주세요 : ")
num

'5'

In [54]:
#print()함수
for i in range(10) :
    print(i)


0
1
2
3
4
5
6
7
8
9


In [57]:
for i in range(10) :
    print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 

In [58]:
#list()함수, tuple()함수
list("hello")

['h', 'e', 'l', 'l', 'o']

In [63]:
list((1,2,3,4,5))

[1, 2, 3, 4, 5]

In [64]:
#enumerate()
for i, name in enumerate(['a','b','C','D','E','F','G','H']) :
    print(i, name)

0 a
1 b
2 C
3 D
4 E
5 F
6 G
7 H


### 파일 읽고 쓰기

#### 파일 생성 함수 open()
* open()함수 구조

파일 객체명 = open(파일명(패스포함), 파일모드)
파일객체명.close

* 파일모드
<table>
<tr><th>파일모드</th><th>설명</th></tr> 
<tr><td>r</td><td>읽기모드 : 파일을 읽어올때 지정</td></tr>
<tr><td>w</td><td>쓰기모드 : 파일에 내용을 쓸 때 사용</td></tr>
<tr><td>a</td><td>추가모드 : 파일의 마지막에 새로운 내용을 추가할 때 사용</td></tr>
</table>


In [66]:
#파일 쓰기 예제
f = open("test.txt",'w')
for i in range(1,11) :
    data = "%d번째 줄입니다.\n" % i
    f.write(data)
f.close()    

In [ ]:
#파일 전체 라인 읽어오기 1
f = open('test.txt','r')
while True :
    line = f.readline()
    if not line : break
    print(line)
f.close()

In [72]:
#파일 전체 라인 읽어오기 2
f = open('test.txt','r')
lines = f.readlines()
for line in lines :
    line = line.strip()
    print(line)
f.close()

1번째 줄입니다.
2번째 줄입니다.
3번째 줄입니다.
4번째 줄입니다.
5번째 줄입니다.
6번째 줄입니다.
7번째 줄입니다.
8번째 줄입니다.
9번째 줄입니다.
10번째 줄입니다.


In [74]:
# 파일을 통으로 읽어오기
f = open('test.txt', 'r')
data = f.read()
print(data)
f.close()

1번째 줄입니다.
2번째 줄입니다.
3번째 줄입니다.
4번째 줄입니다.
5번째 줄입니다.
6번째 줄입니다.
7번째 줄입니다.
8번째 줄입니다.
9번째 줄입니다.
10번째 줄입니다.



In [76]:
#파일 객체를 사용해서 읽어오기
f = open('test.txt', 'r')
for line in f :
    line = line.strip()
    print(line)
f.close()    

1번째 줄입니다.
2번째 줄입니다.
3번째 줄입니다.
4번째 줄입니다.
5번째 줄입니다.
6번째 줄입니다.
7번째 줄입니다.
8번째 줄입니다.
9번째 줄입니다.
10번째 줄입니다.


In [78]:
#파일 추가 모드
f = open('test.txt', 'a')
for i in range(11,20) :
    data = "%d번째 줄입니다.\n" % i
    f.write(data)
f.close()    
    
         

In [89]:
#파일 읽기 예제
data = []
f = open('대전광역시.txt', 'r',encoding='utf-8')
for i in range(10) :
    line = f.readline()
    line = line.strip()
    line = line.replace('\ufeff','')
    data_record = line.split('|')
    data.append(data_record)
print(data)
f.close()

[['우편번호', '시도', '시도영문', '시군구', '시군구영문', '읍면', '읍면영문', '도로명코드', '도로명', '도로명영문', '지하여부', '건물번호본번', '건물번호부번', '건물관리번호', '다량배달처명', '시군구용건물명', '법정동코드', '법정동명', '리명', '행정동명', '산여부', '지번본번', '읍면동일련번호', '지번부번', '구우편번호', '우편번호일련번호'], ['34316', '대전광역시', 'Daejeon', '대덕구', 'Daedeok-gu', '', '', '302303010005', '대청호수로', 'Daecheonghosu-ro', '0', '1553', '0', '3023012100102380008004335', '', '갈밭식당', '3023012100', '갈전동', '', '신탄진동', '0', '238', '02', '8', '', ''], ['34316', '대전광역시', 'Daejeon', '대덕구', 'Daedeok-gu', '', '', '302303010005', '대청호수로', 'Daecheonghosu-ro', '0', '1506', '0', '3023012100105030000000001', '', '', '3023012100', '갈전동', '', '신탄진동', '0', '503', '02', '0', '', ''], ['34316', '대전광역시', 'Daejeon', '대덕구', 'Daedeok-gu', '', '', '302303010005', '대청호수로', 'Daecheonghosu-ro', '0', '1536', '34', '3023012100104980000000001', '', '', '3023012100', '갈전동', '', '신탄진동', '0', '498', '02', '0', '', ''], ['34316', '대전광역시', 'Daejeon', '대덕구', 'Daedeok-gu', '', '', '302303010005', '대청호수로', 'Daecheonghosu

In [91]:
#클래스 정의 및 객체 생성
class Calculator :
    def __init__(self) :
        self.result = 0
    
    def add(self, num) :
        self.result += num
        return self.result
    
cal1 = Calculator()    

cal1.add(1)


1

In [ ]:
# 모듈 사용
import sys
sys.exit()

import numpy as np

from 패키지명 import 선택모듈
from 패키지명 import 선택모듈1, 선택모듈2
from 패키지명 import 선택모듈 as 별칭


In [ ]:
#모듈 설치
%pip install numpy


# 데이터를 처리하기 위한 모듈
## (1) numpy
* 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 패키지
* 루프를 사용하지 않고 대량 데이터의 배열 연산을 가능
* 데이터 분석, AI 분야 뿐만 아니라 자연과학, 공학에서도 널리 사용

In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3,4,5])
print(array1, type(array1))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [3]:
array1.shape

(5,)

In [5]:
array2 = np.array([[1,2,3],[4,5,6]])
print(array2, array2.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [6]:
array3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array3, array3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] (2, 2, 3)


In [7]:
print('array1:{0}차원, array2:{1}차원, array3:{2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1:1차원, array2:2차원, array3:3차원


In [11]:
array1 = np.arange(10)
print(array1, array1.shape)

[0 1 2 3 4 5 6 7 8 9] (10,)


In [14]:
array2 = array1.reshape(5,2)
print(array2, array2.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] (5, 2)


In [16]:
array3 = array1.reshape(5,-1)
print(array3, array3.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] (5, 2)
